#chore Make ESLint mandatory

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -5,7 +5,10 @@
 npm run lint
 
 # Run Prettier to format your code
-npm run format
+if ! npm run lint; then
+  echo "Error: ESLint failed. Aborting commit."
+  exit 1
+fi
 
 # Run your Jest tests
 if ! npm run test-jest; then
