#chore Husky update

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,14 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
+# Run your linter
+npm run lint
+
+# Run Prettier to format your code
 npm run format
+
+# Run your Jest tests
+if ! npm run test-jest; then
+  echo "Error: Jest tests failed. Aborting commit."
+  exit 1
+fi
